[package]
name = "scout_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
rand = "0.8"
rand_xoshiro = "0.6"

[profile.release]
lto = true
code-gen-units = 1

[[bin]]
name = "search"
path = "src/main_search.rs"

[[bin]]
name = "qlearner"
path = "src/main_qlearner.rs"
